# Generated by Django 2.1.15 on 2020-05-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdetails',
            name='contact',
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
